version: "3.3"

services:
  monopoly-postgres-service:
    image: postgres:13.2
    container_name: monopoly-postgres-service
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: monopoly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - monopoly-app-network

  monopoly-backend-service:
    image: platypuses/monopoly-backend:latest
    container_name: monopoly-backend-service
    restart: always
    expose:
      - 8080
    environment:
      PORT: 8080
      POSTGRES_DB_HOST: monopoly-postgres-service
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_USERNAME: postgres
      POSTGRES_DB_PASSWORD: postgres
      POSTGRES_DB_NAME: monopoly
    networks:
      - monopoly-app-network
    depends_on:
      - monopoly-postgres-service

  monopoly-frontend-service:
    image: platypuses/monopoly-frontend:latest
    container_name: monopoly-frontend-service
    restart: always
    expose:
      - 80
    environment:
      BACKEND_BASE_URL: http://monopoly-api.casper.by/api/v1
    networks:
      - monopoly-app-network
    depends_on:
      - monopoly-backend-service

  monopoly-nginx-service:
    image: nginx:1.19.10-alpine
    container_name: monopoly-nginx-service
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/monopoly.conf:/etc/nginx/conf.d/default.conf
    networks:
      - monopoly-app-network
    depends_on:
      - monopoly-backend-service
      - monopoly-frontend-service

volumes:
  postgres-data:

networks:
  monopoly-app-network:
