version: "3.3"

services:
  monopoly-postgres-service:
    image: postgres:13.2
    container_name: monopoly-postgres-service
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: monopoly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - monopoly-app-network

  monopoly-backend-service:
    image: platypuses/monopoly-backend:latest
    container_name: monopoly-backend-service
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      POSTGRES_DB_HOST: monopoly-postgres-service
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_USERNAME: postgres
      POSTGRES_DB_PASSWORD: postgres
      POSTGRES_DB_NAME: monopoly
    networks:
      - monopoly-app-network
    depends_on:
      - monopoly-postgres-service

  monopoly-frontend-service:
    image: platypuses/monopoly-frontend:latest
    container_name: monopoly-frontend-service
    restart: on-failure
    ports:
      - 80:80
    environment:
      BACKEND_BASE_URL: http://localhost:8080/api/v1
    networks:
      - monopoly-app-network
    depends_on:
      - monopoly-backend-service

volumes:
  postgres-data:

networks:
  monopoly-app-network:
